### PR TITLE
Add hasNotch()

### PR DESCRIPTION
**Pull request by diegolmello**
## Description

Fixed issue #427 

Added hasNotch() that returns a boolean if the device has a notch.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |
| Windows |    ✅❌     |

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [x] I added the documentation in `README.md`.
* [ ] I mentionned this change in `CHANGELOG.md`.

### CODE REVIEW

**Comment by machour** [comment]
@ddobby94 is it possible on these devices to disable/enable the notch? If so, do you think it's something we can detect at runtime?

**Comment by machour** [comment]
@diegolmello Thank you for this PR. Maybe we could name this `hasNotch()` instead? 🤔

**Comment by kashishgrover** [comment]
please merge 😄

**Comment by machour** [comment]
@diegolmello could you add those Android devices before I merge?  :pray:

**Comment by diegolmello** [comment]
@machour Done! 👍

**Comment by machour** [comment]
Just published 0.23.0 with hasNotch()

Thank you @diegolmello & @ddobby94

**Pull request merged**
