### PR TITLE
Feature/android sdk 28

### PR DESCRIPTION
**Pull request by justinmakaila**
## Description

Updates to android sdk 28

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |
| Windows |    ❌     |

## Checklist

* [ ] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`.
* [ ] I mentioned this change in `CHANGELOG.md`.

### CODE REVIEW

**Comment by machour** [comment]
Apologies for not getting back to you sooner.
Is this safe to ship in 0.27.0 ? Will this break existing apps using this lib ?

**Comment by puranjayjain** [comment]
I think this change will impact the people targeting lower SDK versions as this changes the default target SDK version.

**Comment by BenWildeman** [comment]
you can make sure all your submodules target the same SDK you're using by doing the following in your root build.gradle file:

```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion "28.0.3"
            }
        }
    }
}
```

**Comment by mikehardy** [comment]
This change should have small impact (or, a diminishing, user-controllable impact) as the react-native style for android builds has changed such that everyone should be controlling their gradle versions in their own app build.gradle

you can see the versions are checked for external definition here so this change will only effect people that haven't changed to the new style yet https://github.com/rebeccahughes/react-native-device-info/blob/master/android/build.gradle

**Comment by mikehardy** [comment]
@machour I think this should merge, people should have specific versions set in their app/build.gradle if they want to control them.

@justinmakaila if you could also PR a sample app that's just a fresh react-native init with this linked in that would be fantastic. I mention that because for targetSdk API28 people have to be careful of plaintext loading in Android (like this https://github.com/Microsoft/reactxp/pull/1048/commits/5558bddebd1972d1ac044bde9e507f0f01c6d928#diff-6ce28bd386e24468a9ee538ca35dabf8) or their dev build will break, and it will decrease support load if there is an example and we can point to it

**Comment by machour** [comment]
react-native-device-info 0.28.0 published 🎉

(did this one last so that we have 0.28.0 for sdk 28 🤓)

**Pull request merged**
