### PR TITLE
improve README

### LINKED ISSUE #74: rnpm install doesn't work on Android
```rnpm install ``` installs package only on iOS. 
The only I find to install it on Android is the manual installation.

### PR DESCRIPTION
**Pull request by antoinerousseau**
fixes #74

hope you like it :)

### CODE REVIEW

**Comment by GantMan** [comment]
:star2: WOW! :star2:, LGTM!  Any feedback @mehcode before I merge?

**Comment by GantMan** [comment]
@antoinerousseau - can you please fix the small merge-conflict so I can merge?

**Comment by antoinerousseau** [comment]
Ok! I'll do it tomorrow :)

**Comment by antoinerousseau** [comment]
@GantMan done!

**Comment by mehcode** [comment]
@antoinerousseau Looks nice! (not sure why I was pinged but I'll come on and say "looks nice" when it does indeed look nice).

You did forget to mention the uniqueId changes for iOS in the changelog. I'm not sure when it was released but `getUniqueId` is _persistent_ after one of last PRs (it reset on app uninstall before).

**Comment by antoinerousseau** [comment]
@mehcode I'm not sure what you are talking about, the [release notes](https://github.com/rebeccahughes/react-native-device-info#release-notes) currently on `master` are the same than the [CHANGELOG](https://github.com/antoinerousseau/react-native-device-info/blob/doc/CHANGELOG.md) in this PR, no?

**Comment by GantMan** [comment]
@mehcode - I pinged you because you show up :)

**Pull request merged**
