### PR TITLE
fix: Moved the IOS code to an ios/ directory

### PR DESCRIPTION
**Pull request by rhdeck**
## Description
Fixed issue #353 by moving the IOS code to a more-easily-findable location
## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`. (bug fix - not go in?)
* [ ] I mentioned this change in `CHANGELOG.md`. (bug fixes go here?)

### CODE REVIEW

**Comment by machour** [comment]
Thank you @rhdeck, I always meant to do that but I didn't know this was affecting linking!

Do you have any documentation / pointer to source code that shows that RN does indeed look for things in `ios/`? I had a look at the source code and couldn't find that, but I certainly missed it.

**Comment by IljaDaderko** [comment]
@machour I'm not sure whats the best way to mention this in docs / readme. But this is a breaking change that will require re-linking for people as RNDeviceInfo changed location.

**Comment by sibelius** [comment]
You should unlink and relink again to make it work

**Comment by thiswhy** [comment]
1. open xcode with your project
2. click your project name 
3. select Build Phases
4. select link Binary With Libraries
5. remove libRNDeviceInfo-tvOS.a
6. 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
