### PR TITLE
don't pin gradle dependency versions

### LINKED ISSUE #78: Please don't pin your play-services dependency at a particular version
It causes issues **with other libs** when a 3rd-party library, like yours, pins its `play-services` dependencies at a particular version.

eg:
```
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)
```

You have
```Gradle
compile 'com.google.android.gms:play-services-gcm:8.3.0'
```

You need to change it to:
```Gradle
compile 'com.google.android.gms:play-services-gcm:+'
```

### PR DESCRIPTION
**Pull request by antoinerousseau**
fixes #78

### CODE REVIEW

**Comment by antoinerousseau** [comment]
Worked for me after getting this error when trying to make it work with `react-native-fcm`:
```
:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/measurement/AppMeasurementContentProvider;
Unknown source file :  	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :  	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :  	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :  	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :  	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :  	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :  	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :  	at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by GantMan** [comment]
Fixes #78

**Comment by lukefanning** [comment]
@rebeccahughes Hi, can we get a new package with this?

**Comment by GantMan** [comment]
rndi 0.9.5 published

**Comment by lukefanning** [comment]
@GantMan thanks for that

**Pull request merged**
