### PR TITLE
Add support for phone number.

### PR DESCRIPTION
**Pull request by passabilities**
Adds ability to grab the phone number of the device in Android.

### CODE REVIEW

**Comment by GantMan** [comment]
needs docs in readme

**Comment by ferdicus** [comment]
Hey there, is there an ETA / can I find the info in a roadmap on when this PR is going to be merged?

Thanks in advance

**Comment by passabilities** [comment]
Haven't heard anything. Feel free to use my fork if you need the feature now:

https://github.com/passabilities/react-native-device-info
Branch `phone-number`

**Comment by GantMan** [comment]
@passabilities - please resolve conflicts and ping me when you have the updated code so I can merge.

**Comment by passabilities** [comment]
@GantMan hows this?

**Comment by GantMan** [comment]
Thanks!

**Pull request merged**
