### PR TITLE
fix: remove deprecated React pod dependency

### PR DESCRIPTION
**Pull request by IljaDaderko**
## Description

Fixed issue #352

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
| Windows |    ✅     |

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [x] I added the documentation in `README.md`. (Not needed)
* [ ] I mentionned this change in `CHANGELOG.md`.

### CODE REVIEW

**Comment by machour** [comment]
Thank you @IljaDaderko !

**Comment by IljaDaderko** [comment]
@machour sick! I will work with it latter today, will let you know if I notice something weird.

**Comment by IljaDaderko** [comment]
@machour I ran into an issue with fresh implementation

`RCTBridgeModule` is not defined and as far as I can see it is checking that it is initially in React pod. Any ideas for fix here? It has fallback to just include this file, but it is not inside pod directory.

screen shot 2018-03-17 at 14 57 31

**Comment by IljaDaderko** [comment]
Going deeper into this, I don't think pod approach is working, I linked everything manually following "ios without cocoapods" guide and it works fine. I think "ios with pods" needs to be updated, especially since it prob wasn't touched for a while? (judging by left in React pod).

Some observations

1) Installing pod doesn't link it to project `Libraries`
2) Pod is installed as `Development Pod`

I think its worth to re-open this issue.

**Comment by koenpunt** [comment]
Since the `React` pod has no version constraint in the podspec, it will rely on the latest version available, which will be the React version added to your project. Removing this dependency will make it unable to resolve the `RCTBridgeModule.h`, like @IljaDaderko [already mentioned](https://github.com/rebeccahughes/react-native-device-info/pull/361#issuecomment-373918914).
I think this change should be reverted.

**Comment by IljaDaderko** [comment]
Agreed, I probably had this cached when I was testing in my project hence, didn't catch it. However, adding React pod back in completely hands pod install (or takes more than 5 min to resolve React pod, I waited this long and gave up).

**Comment by machour** [comment]
@IljaDaderko add --verbose when using `pod install`, this will shade some lights on what's going on. It was a pretty huge download on my side.

@koenpunt I downloaded CocoaPods and tried adding this project on a fresh crna app. From what I'm understanding from the [docs](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies), the reference to React should be made in the application Podfile itself. 

RNDeviceInfo would resolve whatever React is installed by the developer.

Tried this on my end, but I'm facing some unrelated errors from Yoga. Could you confirm / correct me if I'm wrong?

**Comment by koenpunt** [comment]
> RNDeviceInfo would resolve whatever React is installed by the developer.

True, but from my experience; if the dependency is not specified in the podspec, the generated project will not include a header search for the React files, so the dependency declaration is still necessary.

**Comment by machour** [comment]
/summon @GantMan 

Hey Gant, could you shade some lights on this PR and what should be done with pods?

Some people are complaining about having React (deprecated) as a dependency in our podspec. (#38, #63, #352)

I thought that sticking to Facebook recommended way should be fine, but it seems that it would cause problems.

**Comment by fjtrujy** [comment]
Hello,

I'm pretty sure that the React dependency should be kept.
It is mandatory to be used with Cocoapods.
I don't understand why there are people complaining about this dependency, they said that this is deprecated... but I don't find the official documentation where they said about how to make it work with Cocoapod and react-native.

Can you help me with this?

Thanks

**Comment by machour** [comment]
@fjtrujy Here's the documentation I found that lead me to believe that the React pod must be required from the application `Podfile`, not libraries podspecs: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies

I do however understand that dropping this dependency is problematic, and my knowledge is really limited on the subject as I don't use pods at all. 

I think I'll simply rollback this change, as having a warning about deprecation is far less problematic than having problems compiling your app.

PS: for now, you can stick with 0.21.0 until this gets sorted out.

**Comment by machour** [comment]
Really curious about what you have done for the web platform, I was under the impression that we would only be able to provide an empty polyfill, by all means, go ahead! 🙌 

No need to PR the rollback, just waiting to see if @GantMan have the time to have a look before changing that one line.

**Comment by fjtrujy** [comment]
Actually is not just about web, is about native snapshots using jest (that are the end runs over a browser), right now the project is not compatible with this.

Thanks

**Comment by fjtrujy** [comment]
I have created the PR for the snapshots.

Thansk!

https://github.com/rebeccahughes/react-native-device-info/pull/375

**Comment by EyMaddis** [comment]
This rollback issue now installs React (again) in an older version when using it in a project that does not use cocoapods for every dependency.

**Pull request merged**
