### PR TITLE
Update buildToolsVersion to 25.0.1

### PR DESCRIPTION
**Pull request by jaggs6**
Need to update this in order to use with the latest build tools

### CODE REVIEW

**Comment by mquander** [comment]
+1, I had to do this and it would be nice to have in upstream.

**Comment by jaggs6** [comment]
Thanks for merging this. Would be great if we can update the npm version as well.

**Comment by GantMan** [comment]
there's one more PR coming that I would want.  Give me a min to wait for that one then release.

**Comment by huston007** [comment]
That's good to keep latest versions, but React Native itself [still uses 23.0.1](http://facebook.github.io/react-native/releases/0.42/docs/getting-started.html#android-development-environment) version. So now I should have both versions installed just to get compiled one of dependencies. 
I don't think that's really straightforward.

**Comment by mquander** [comment]
It's true that it says that in the docs, but in your React Native application it's easy to set the build tools version to whatever you like in your build.gradle.

It's possible that there is some reason they preferred 23.0.1 by default though -- I have no idea.

**Pull request merged**
