### PR TITLE
Add support for web browsers.

### PR DESCRIPTION
**Pull request by peacechen**
## Description

Add support for web browsers. See #323

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| Web     |    ✅     |

## Checklist

* [.. ] I have tested this on a device/simulator for each compatible OS (tested on iOS)
* [X ] I added the documentation in `README.md`.
* [ ] I mentionned this change in `CHANGELOG.md`.  (creating PR now so don't have the #)

### CODE REVIEW

**Comment by peacechen** [comment]
Hold off on merging this until I validate it in a working react-native-web project.

**Comment by peacechen** [comment]
I've updated this PR and validated it's working for react-native-web.

**Comment by machour** [comment]
Hey @peacechen, sorry for not getting back to you earlier.

After some more thinking, I think that it would be better not to consider "web" a target for react-native-device-info, but I don't have any problems with providing an empty polyfill for react-native-web developers.

Opened #339 to provide this, based on your PR. Could you give it a review?

**Comment by peacechen** [comment]
Thanks @machour 
Replied to your PR

**Pull request closed without merging**
