### PR TITLE
check to detect is iphone x of not

### PR DESCRIPTION
**Pull request by fattahmuhyiddeen**
## Description

Added `isIphoneX()` that allows to check if user are using iphoneX

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS          |    ✅     |
| Android   |    ✅     |
| Windows |    ✅    |

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [x] I added the documentation in `README.md`.
* [x] I mentionned this change in `CHANGELOG.md`.

### CODE REVIEW

**Comment by machour** [comment]
Hi and thank you for your proposal. 
Have you tried using getModel() and encountered problems?

DeviceInfo.getModel() === 'iPhone X';

**Comment by fattahmuhyiddeen** [comment]
yes I already use it. currently from my forked version

**Comment by machour** [comment]
isIphoneX() is really easy to replicate in your application using:

```
const isIphoneX = () => DeviceInfo.getModel() === 'iPhone X';
```

Adding it to this library doesn't really make sense to me (or else we will end up with isSamsungS8(), isOnePlus5t(), etc..).

**Comment by fattahmuhyiddeen** [comment]
it make sense because iphonex has notch and i really need make my app
header taller just for that iphone to avoid that notch

**Comment by fattahmuhyiddeen** [comment]
starting april, apple force all app to compatible with iphone x ui

**Comment by machour** [comment]
I hear you, but reac-native-device-info is about pulling native information from devices, in the most generic / cross-platform way possible.

Adding isIphoneX() would break that promise, and we already provide `getModel()` that allow you to quickly do it in your app.

**Comment by fattahmuhyiddeen** [comment]
ok

**Comment by machour** [comment]
Please feel free to submit other PRs at any time 🙌

**Pull request closed without merging**
