### PR TITLE
Made changes to get imei, imsi and msisdn

### PR DESCRIPTION
**Pull request by parthipank**
Currently there is no way to get the IMEI, IMSI and MSISDN of an android device using this device.
So i made use if TelephonyManager in this repo to get these details.

1.Edited RNDeviceModule.java to get imei, imsi and msisdn of an android device.
  Used TelephonyManager library for this.

2.Edited deviceinfo.js for the getters.

### CODE REVIEW

**Comment by wk1017553772** [comment]
why do not merge it? because conflicts？？

**Comment by GantMan** [comment]
fix the conflicts, update changelog, and message me, I'll merge.

**Comment by machour** [comment]
Hi there!

I'm a new maintainer on this project and I'm trying to clear the PR queue.
Are you still available to bring this PR up to date with latest changes and discuss it?

Please let me know, thank you!

**Comment by falcucci** [comment]
@machour is there any news about it? if no one can put this up to date I can do it.

**Pull request closed without merging**
