### PR TITLE
Adde getDeviceIDFA,getMobileService,getCurrentBatteryPercent,getCurre…

### PR DESCRIPTION
**Pull request by DanielProj**
Added getDeviceIDFA,getMobileService,getCurrentBatteryPercent,getCurrentNetworkType method for iOS

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
Current network type is exposed via the react-native netinfo APIs

**Comment by ThisIsMissEm** [comment]
Pretty sure IDFA is in core (AdSupportIOs)

**Comment by machour** [comment]
Hi there!

I'm a new maintainer on this project and I'm trying to clear the PR queue.
Are you still available to bring this PR up to date with latest changes and discuss it?

Please let me know, thank you!

**Comment by ThisIsMissEm** [comment]
No, it's been over a year, I don't work in tech anymore.

**Comment by machour** [comment]
@ThisIsMissEm are you the original pull request submitter?

**Pull request closed without merging**
