### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by jkimbo**
Did my best to update the changelog with older versions and changes to come

### CODE REVIEW

**Comment by jkimbo** [comment]
Would also be great to release a new version since there a quite a lot of (great) changes waiting. Let me know if you need any help.

**Comment by jkimbo** [comment]
Fixes https://github.com/rebeccahughes/react-native-device-info/issues/216

**Comment by GantMan** [comment]
great work!  thanks so much

**Comment by antoinerousseau** [comment]
thanks @jkimbo !!

**Pull request merged**
