### PR TITLE
Switched to Firebase from gcm

### PR DESCRIPTION
**Pull request by w0nche0l**

### CODE REVIEW

**Comment by richardgill** [comment]
So if you use this, you have to have a `google-services.json` which changes the barrier to entry significantly for this module.

Anyone know of a better solution?

**Comment by RaphArbuz** [comment]
I do have a conflicting issue between gcm and fcm because I use react-native-device-info.
What is the status of that branch?
Many thanks.

**Comment by GantMan** [comment]
Try this:  https://github.com/infinitered/ignite/blob/master/ignite-base/android/app/build.gradle#L147-L155

Please let me know if it works.

**Comment by RaphArbuz** [comment]
Hi @GantMan . Sorry to have been long to get back to you. No it's not changing anything unfortunately. I don't think it's a gcm version issue but a gcm + fcm one. I may have to do without react-native-device-info if that does not work unfortunately. 

Many thanks for your help.

**Comment by nikDemyankov** [comment]
Hi @RaphArbuz, 
Not sure if it's valid for you anymore, but maybe someone else will hit the same problem.

The issue is that both libraries use different versions of `com.google.android.gms`. The solution is the following:

In your `app/build.gradle` find
```
dependencies {
    compile project(':react-native-device-info')
    compile project(':react-native-firebase')
```

And change it to:
```
dependencies {
    compile (project(':react-native-device-info')) {
        exclude group: "com.google.android.gms"
    }
    compile 'com.google.android.gms:play-services-gcm:$firebaseVersion'
    compile project(':react-native-firebase')
```

The value of `$firebaseVersion` should be set to the version that is used in the `react-native-firebase` library. For instance:
```
dependencies {
    compile (project(':react-native-device-info')) {
        exclude group: "com.google.android.gms"
    }
    compile 'com.google.android.gms:play-services-gcm:10.2.6'
    compile project(':react-native-firebase')
```

After that I've managed to build and run the project.

**Comment by RaphArbuz** [comment]
Thanks @nikDemyankov I'm a bit back in times now for me to remember what was going on there but it may help some other coders around here.

**Comment by machour** [comment]
Hi there!

I'm a new maintainer on this project and I'm trying to clear the PR queue.
Are you still available to bring this PR up to date with latest changes?

Please let me know, thank you!

**Comment by richardgill** [comment]
I've used this module in projects with firebase without issues, so it's not a problem for me anymore I think? Although I struggle to remember what the problem was so long ago.

**Comment by machour** [comment]
@richardgill thank you for your feedback! Not sure if this is needed anymore either since a lot of things changed..

**Comment by machour** [comment]
Closing this stale PR.

**Pull request closed without merging**
