### PR TITLE
add typescript types

### PR DESCRIPTION
**Pull request by gyzerok**
Hello!

Thanks for creating such a helpful package! We are using this package with TypeScript in our project so I've thought it would be nice to contribute back a bit :)

### CODE REVIEW

**Comment by gyzerok** [comment]
@rebeccahughes ping

**Comment by GantMan** [comment]
looks good!

**Comment by gyzerok** [comment]
@GantMan hello! Can we have a new release with this addition?

**Comment by GantMan** [comment]
published 0.10.2!

**Pull request merged**
