### PR TITLE
Extend DeviceInfo Modul with functions for Storage Space (Android)

### PR DESCRIPTION
**Pull request by BigPun86**
- add function getAvailableExternalMemorySize() and getAvailableInternalMemorySize() to get informations about storage space

### CODE REVIEW

**Comment by mehcode** [comment]
:-1: This belongs in https://github.com/johanneslumpe/react-native-fs not in this simple device query plugin.

**Comment by machour** [comment]
@BigPun86 a fresher PR was created for iOS, with a better naming. Do you mind if your code is borrowed for #302 and this PR get closed?

**Comment by BigPun86** [comment]
Sure, Go ahead 💪🏽

**Comment by machour** [comment]
Thank you buddy!

**Comment by machour** [comment]
FYI, the new PR just made it, it should be live in 0.15.0 in a few days.

**Pull request closed without merging**
