### PR TITLE
Added iOS/Android support for getting carrier information

### PR DESCRIPTION
**Pull request by Naoto-Ida**

### CODE REVIEW

**Comment by GantMan** [comment]
Thanks Naoto

**Comment by Naoto-Ida** [comment]
Hi @GantMan do you have an ETA on when this and other changes will be on the next NPM release?

**Comment by GantMan** [comment]
Shipped 0.13.0!  Enjoy

**Comment by Naoto-Ida** [comment]
Awesome! Thanks @GantMan

**Pull request merged**
