### PR TITLE
- Fixed bundleId, appVersion, buildNumber.

### PR DESCRIPTION
**Pull request by avishayil**

### CODE REVIEW

**Comment by GantMan** [comment]
was there a ticket where this was complained about?  So we can reference the two?

**Comment by mehcode** [comment]
@avishayil What exactly are you doing here. There is little difference between master and this PR.

**Comment by avishayil** [comment]
It didn’t work for me on the iOS side, so I entered the code and found the
solution on the internet, now it’s working.
I have zero knowledge on Obj-C.


On July 4, 2016 at 1:30:57 PM, Ryan Leckey (notifications@github.com) wrote:

@avishayil <https://github.com/avishayil> What exactly are you doing here.
There is little difference between master and this PR.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rebeccahughes/react-native-device-info/pull/56#issuecomment-230259515>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAyekOP0PQTbl4hGyzytsqUe2HmItHqvks5qSODhgaJpZM4I8jOn>
.

**Comment by antoinerousseau** [comment]
@avishayil what exactly was the problem?

**Pull request closed without merging**
