### PR TITLE
Create a new project to fix RNW version compatability and ReactWindows project reference  error

### PR DESCRIPTION
**Pull request by jmcginty**
## React Native Windows has a minimum target version of 10.0.14393, and react native device info needs to be updated or projects will not compile. 

Also, this fixes another existing bug where the reference to the ReactNative project in the csproj was wrong.

Fixed issue #505 Does not support React Native Windows v0.57
Fixed issue #151 Does not build when running react-native run-windows
## Checklist

* [X ] I have tested this on a device/simulator for each compatible OS
* [ X] I mentionned this change in `CHANGELOG.md`.

### CODE REVIEW

**Comment by machour** [comment]
Hi and sorry for the delays. Could you fix the merge conflicts ?

**Comment by jmcginty** [comment]
Conflicts fixed !

**Comment by machour** [comment]
Thank you so much. Unfortunately my PC which had a RNW setup died on me a while ago, so I cannot test my old project and see how this PR affects it. 

How will things go with people already using this library on react native windows ? Are there breaking changes, or some adjustments to be made to be able to compile?

**Comment by jmcginty** [comment]
On our project, we were already using react-native-device-info, and only encountered this problem while upgrading to RNW 0.57. After changing the package.json file to refer to the pull request project, it works and no source code adjustments were needed. We were able to delete some workarounds for #151, but no changes other than this.

**Comment by machour** [comment]
And for people on RNW < 0.56, how would that go? :thinking:

**Comment by jmcginty** [comment]
We upgraded from RNW 0.50 to 0.57, so it should go fine.

**Comment by machour** [comment]
All right thanks. I'll merge it when I have access to my laptop :)

**Comment by jmcginty** [comment]
Actually, I did some more testing on an older project, and found that because the .csproj file has moved down one level in the directory structure, it would be better if I moved it back up one level and upgrading would be smoother. Please wait until I make this change before merging.

**Comment by jmcginty** [comment]
The .csproj file is in the same location now, so older projects will just find it where they expect it. The only caveat I guess is that now react-native-device-info has a minimum version of 10.0.14393, the host project will have to have a minimum of this version or higher.

**Comment by machour** [comment]
Thank you so much, just added a quick note in the changelog about the new minimal requirement.

0.24.3 has just been published! 🎉

**Pull request merged**
