### PR TITLE
Add timezone to information provided by module.

### PR DESCRIPTION
**Pull request by juankiz**

### CODE REVIEW

**Comment by juankiz** [comment]
Hey @rebeccahughes any comments on the pr?

**Comment by GantMan** [comment]
@juankiz  - Can you please implement this on Android as well?  I think this library is keen on keeping parity between iOS and Android.

Also, you might be able to do this with a 100% javascript solution right?   
`let offset = new Date().getTimezoneOffset();`

**Comment by mehcode** [comment]
Added a java impl on https://github.com/rebeccahughes/react-native-device-info/pull/59

@GantMan Not possible to get an Olson formatted timezone form javascript.

**Comment by GantMan** [comment]
Closed via #59

**Pull request closed without merging**
