### PR TITLE
feat: add getInstallReferrer() for Android

### PR DESCRIPTION
**Pull request by poison**
## Description

Added `getInstallReferrer()` that returns the install referrer attribution when your android app gets installed (com.android.vending.INSTALL_REFERRER). You can use https://play.google.com/store/apps/details?id=com.myapp&referrer=<your custom referrer string here>

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |   ❌     |
| Android |    ✅    |
| Windows |   ❌     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [X] I added the documentation in `README.md`.
* [ ] I mentionned this change in `CHANGELOG.md`.

### CODE REVIEW

**Comment by poison** [comment]
This feature can be tested with the following command:

`adb shell am broadcast -a com.android.vending.INSTALL_REFERRER -n com.test/com.learnium.RNDeviceInfo.RNDeviceReceiver --es "referrer" "This_is_my_custom_referrer"`

Please change com.test with your application identifier

**Comment by machour** [comment]
Hi @poison and thank you so much for this proposal!
Do you think this can be made iOS compatible as well?

**Comment by poison** [comment]
Hi @machour , as far as I know there is no such built-in functionality on iOS, most of the 3rd party solutions out there rely on device fingerprinting and attribution.

For example, you can create links to an custom url shortener, which logs the IP address, User-Agent and iOS version (server-side), and redirects the user to the app store. Once your app is launched you do the same request from within your app to the url shortener. The shortener tries to match the data and returns the HTTP_REFERER of the initial link. Since this is all custom and currently not supported by Apple I left it out. I think this blogs explains it well: [https://blog.attributionapp.com/lets-solve-ios-attribution-methods](https://blog.attributionapp.com/lets-solve-ios-attribution-methods)

**Comment by poison** [comment]
Any comments/suggestions on how to proceed?

**Comment by machour** [comment]
Had a busy week, sorry for not getting back to your earlier. Thank you for getting back to me about iOS, I guess will stick to Android only support for now :)

I'll review and merge this PR this week!

**Comment by machour** [comment]
Thank you 🙌

**Comment by poison** [comment]
Oh, I just realized on the documentation (README.me) I forgot to add brackets next to the function definition (getInstallReferrer vs getInstallReferrer()) around line 468, not too bad, just cosmetic.

**Comment by machour** [comment]
Fixed thanks!

**Pull request merged**
