### PR TITLE
Use persistent UID for iOS

### PR DESCRIPTION
**Pull request by mehcode**
Primarily taken from https://gist.github.com/miguelcma/e8f291e54b025815ca46 with several small changes to make it work (that script crashes). 

This needs "added" to the iOS project but I don't have a Mac at home. I can guarantee it works and passes iOS review as we're using it in production.

### CODE REVIEW

**Comment by Hitabis** [comment]
+1

**Comment by GantMan** [comment]
Looks good to me.   @mehcode did you have a chance to actually test on device?

**Comment by mehcode** [comment]
@GantMan I have the DeviceUID files in my own project and that is on the app store / works great. I haven't gotten a chance to "add files..." in xcode and do a quick test though. I'll try to get time tomorrow at work.

**Comment by mehcode** [comment]
@GantMan Should be good to. Ran through a few tests after fixing compilation (have a mac at home now).

**Comment by danielreuterwall** [comment]
@rebeccahughes @mehcode Any plans on a new release including this fix?

**Comment by mehcode** [comment]
@GantMan ^

@danielreuterwall I'm not a maintainer so I can't release it.

**Comment by GantMan** [comment]
I have access to the github, but I never got access to the NPM for publish.   Perhaps @rebeccahughes can grant me access, I'll happily do a release.

**Comment by rebeccahughes** [comment]
You should have access now. The release process I usually follow is:

1. Run some tests on iOS and Android to make sure it works :)
2. Bump the version in Info.plist, package.json and android's gradle file
3. Update the Release Notes and README.md with any new info
4. npm publish

**Comment by kevando** [comment]
As of today it seems npm is still not up to date with the most recent code changes, in particular PR #58

**Comment by GantMan** [comment]
I missed Rebecca's message.  I'll be at my computer later today and go through the release process.

**Comment by GantMan** [comment]
Tested with iOS and Android.
Released 0.9.4

**Comment by LeBlaaanc** [comment]
Hey all, seems this was merged in, do we need to update the README I had sent a PR to?

**Pull request merged**
