### PR TITLE
Windows compatibility

### PR DESCRIPTION
**Pull request by josephan**
## React Native Windows

The reason I am making a new PR is because #55 hasn't been updated recently.

For now I have created a dummy response for the method `DeviceInfo.getDeviceName()` and it will return, `"Windows"`. Just to test that it talks to the C# library.

Next l have to implement the remaining constants. To do so I will reference the existing [android](https://github.com/rebeccahughes/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java) implementation and the existing [pull request](https://github.com/rebeccahughes/react-native-device-info/pull/55) for Windows support.

I would love to hear feedback! Thank you!

## Edit
The library has been tested and works.

### CODE REVIEW

**Comment by GantMan** [comment]
looking good!

**Comment by josephan** [comment]
@GantMan Thanks! I just tested it and it works perfectly.

**Comment by GantMan** [comment]
gonna test this soon and hopefully release it in next version.

**Comment by GantMan** [comment]
@josephan please resolve this conflict so I can merge

**Comment by josephan** [comment]
@GantMan I fixed the conflicts and squashed the commits. 😀

**Comment by GantMan** [comment]
great work!

**Pull request merged**
